### ISSUE TITLE
Linux crashes when picking a color | GNOME 42 | Wayland | X11

### ISSUE THREAD

**Issue by flaxflour** [tuberry/color-picker#36]
Whole linux system crashes when picking a color.

System Info:
  Kernel: 5.17.1-arch1-1
  DE: GNOME 42.0

**Comment by kforney** [comment]
Same issue here: the crash doesn't occur every single time, but occasionally, picking a color with this extension causes gnome-shell to crash entirely.

Here's a stack trace from the most recent incident, if it helps at all: [Link to GitHub Gist](https://gist.github.com/kforney/c5aeb393e1d36bb475e31bc61b119296)

**Comment by TomislavBombas** [comment]
Had the same issue on Fedora 36 (Gnome 42, Wayland). Changed the Notification style in extension settings to OSD (default is MSG). Seems to stop the crashes.

**Comment by tuberry** [comment]
Confirmed, It should work after https://github.com/tuberry/color-picker/commit/6517e677e189f216b2395c68361852815159002f. I will find a better fix later.

**Comment by Cherro59** [comment]
Still crashing. Fedora36/Gnome 42/Wayland/5.17.4 kernel

**Comment by sonicnkt** [comment]
Also happens for me sometimes with the latest version and Gnome 42.1 with X11 (NVIDIA) on Manjaro. 
So its not a wayland only problem. 

Tho not the whole system crashes, only Gnomeshell and it restarts automatically after 1-2 Seconds.

**Comment by setuun** [comment]
Also crashing on PopOS 22.04 LTS
Kernel: 5.17.5
Gnome: 42.1

**Comment by ralfstx** [comment]
Crashing also on Ubuntu 22.04 LTS, Gnome 42.1, Wayland.

**Comment by afland** [comment]
same issue

**Comment by tuberry** [comment]
Sorry for the inconvenience, it should be fixed now.

**Comment by setuun** [comment]
@tuberry problem still exists, after system come back from hibernation. here some logs from the crash. the last 50 lines or so are interessting for you, but i give u a bit more log, maybe its important:

```Aug  5 08:58:32 sir-x1extreme kernel: [192831.349299] gnome-shell[3647]: segfault at 18 ip 00007f912f71796e sp 00007ffe928f71b0 error 4 in libgjs.so.0.0.0[7f912f6dd000+9f000]
Aug  5 08:58:32 sir-x1extreme kernel: [192831.349314] Code: ec 30 64 48 8b 04 25 28 00 00 00 48 89 44 24 28 31 c0 e8 55 20 00 00 48 89 c3 e8 4d b4 02 00 48 89 c7 e8 45 d3 02 00 48 89 c5 <48> 8b 43 18 48 85 c0 0f 84 85 00 00 00 48 8b 50 18 48 8d 45 18 49
Aug  5 08:58:33 sir-x1extreme systemd[1]: Started crash report submission.
Aug  5 08:58:33 sir-x1extreme whoopsie[3816411]: [08:58:33] Using lock path: /var/lock/whoopsie/lock
Aug  5 08:58:33 sir-x1extreme systemd[1]: whoopsie.service: Deactivated successfully.
Aug  5 08:58:54 sir-x1extreme systemd[1]: Started crash report submission.
Aug  5 08:58:54 sir-x1extreme whoopsie[3816599]: [08:58:54] Using lock path: /var/lock/whoopsie/lock
Aug  5 08:58:54 sir-x1extreme systemd[1]: whoopsie.service: Deactivated successfully.
Aug  5 08:58:54 sir-x1extreme systemd[2684]: org.gnome.Shell@x11.service: Main process exited, code=dumped, status=11/SEGV
Aug  5 08:58:54 sir-x1extreme systemd[2684]: org.gnome.Shell@x11.service: Failed with result 'core-dump'.
Aug  5 08:58:54 sir-x1extreme systemd[2684]: org.gnome.Shell@x11.service: Consumed 1h 29min 52.419s CPU time.
Aug  5 08:58:54 sir-x1extreme systemd[2684]: org.gnome.Shell@x11.service: Scheduled restart job, restart counter is at 1.
Aug  5 08:58:54 sir-x1extreme systemd[2684]: Stopped GNOME Shell on X11.
Aug  5 08:58:54 sir-x1extreme systemd[2684]: org.gnome.Shell@x11.service: Consumed 1h 29min 52.419s CPU time.
Aug  5 08:58:54 sir-x1extreme systemd[2684]: Starting GNOME Shell on X11...
Aug  5 08:58:54 sir-x1extreme gnome-shell[3816610]: Failed to set RT scheduler: Operation not permitted
Aug  5 08:58:54 sir-x1extreme gnome-shell[3816610]: Running GNOME Shell (using mutter 42.3) as a X11 window and compositing manager
Aug  5 08:58:54 sir-x1extreme gnome-shell[3816610]: Enabling experimental feature 'scale-monitor-framebuffer'
Aug  5 08:58:54 sir-x1extreme thunderbird-bin[4213]: Theme parsing error: gtk-dark.css:9873:19: Junk at end of value for border-radius
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): Eizo EV2736W (DFP-1.2): connected
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): Eizo EV2736W (DFP-1.2): Internal DisplayPort
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): Eizo EV2736W (DFP-1.2): 2660.0 MHz maximum pixel clock
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0):
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): Eizo EV2416W (DFP-1.3): connected
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): Eizo EV2416W (DFP-1.3): Internal DisplayPort
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): Eizo EV2416W (DFP-1.3): 2660.0 MHz maximum pixel clock
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0):
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-0: disconnected
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-0: Internal DisplayPort
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-0: 2660.0 MHz maximum pixel clock
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0):
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-1: disconnected
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-1: Internal DisplayPort
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-1: 2660.0 MHz maximum pixel clock
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0):
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-2: disconnected
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-2: Internal TMDS
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-2: 165.0 MHz maximum pixel clock
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0):
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): Eizo EV2736W (DFP-1.2): connected
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): Eizo EV2736W (DFP-1.2): Internal DisplayPort
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): Eizo EV2736W (DFP-1.2): 2660.0 MHz maximum pixel clock
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0):
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): Eizo EV2416W (DFP-1.3): connected
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): Eizo EV2416W (DFP-1.3): Internal DisplayPort
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): Eizo EV2416W (DFP-1.3): 2660.0 MHz maximum pixel clock
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0):
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-0: disconnected
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-0: Internal DisplayPort
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-0: 2660.0 MHz maximum pixel clock
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0):
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-1: disconnected
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-1: Internal DisplayPort
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-1: 2660.0 MHz maximum pixel clock
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0):
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-2: disconnected
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-2: Internal TMDS
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0): DFP-2: 165.0 MHz maximum pixel clock
Aug  5 08:58:54 sir-x1extreme /usr/libexec/gdm-x-session[2789]: (--) NVIDIA(GPU-0):
Aug  5 08:58:55 sir-x1extreme thunderbird-bin[4213]: Theme parsing error: gtk.css:9952:19: Junk at end of value for border-radius
Aug  5 08:58:55 sir-x1extreme thunderbird-bin[4213]: Theme parsing error: gtk-dark.css:9873:19: Junk at end of value for border-radius
Aug  5 08:58:55 sir-x1extreme thunderbird-bin[4213]: Theme parsing error: gtk-dark.css:9873:19: Junk at end of value for border-radius
Aug  5 08:58:55 sir-x1extreme gsd-media-keys[4131]: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Das Objekt existiert nicht am Pfad »/org/gnome/Shell«
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: Theme parsing error: gtk.css:30:16: not a number
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: Theme parsing error: gtk-dark.css:9873:19: Junk at end of value for border-radius
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: ATK Bridge is disabled but a11y has already been enabled.
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: Theme parsing error: gtk-dark.css:9873:19: Junk at end of value for border-radius
Aug  5 08:58:55 sir-x1extreme thunderbird-bin[4213]: Theme parsing error: gtk-dark.css:9873:19: Junk at end of value for border-radius
Aug  5 08:58:55 sir-x1extreme systemd[2684]: Started dbus-:1.2-org.gnome.ChromeGnomeShell@10.service.
Aug  5 08:58:55 sir-x1extreme thunderbird-bin[4213]: Theme parsing error: gtk.css:9952:19: Junk at end of value for border-radius
Aug  5 08:58:55 sir-x1extreme thunderbird-bin[4213]: Theme parsing error: gtk-dark.css:9873:19: Junk at end of value for border-radius
Aug  5 08:58:55 sir-x1extreme thunderbird-bin[4213]: Theme parsing error: gtk-dark.css:9873:19: Junk at end of value for border-radius
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: Will monitor session 2
Aug  5 08:58:55 sir-x1extreme systemd[1]: Starting Location Lookup Service...
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: Telepathy is not available, chat integration will be disabled.
Aug  5 08:58:55 sir-x1extreme systemd[1]: Started Location Lookup Service.
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: [System monitor] scroll-workspace outer init()
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: [System monitor] scroll-workspace init()
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: [System monitor] scroll-workspace enable()
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: Error: Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: st_widget_get_theme_node called on the widget [0x55c308355dd0 StLabel.vitals-panel-label:insensitive ("…")] which is not in the stage.
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: [popx11gestures@system76.com] Extension enabled
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: [popx11gestures@system76.com] Building entry point for GNOME Shell 42.2
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: [popx11gestures@system76.com] Connecting to Touchégg daemon
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: [popx11gestures@system76.com] Hooking global switch desktop gestures
Aug  5 08:58:55 sir-x1extreme touchegg[1146]: New client connection request
Aug  5 08:58:55 sir-x1extreme touchegg[1146]: New client connected
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: [popx11gestures@system76.com] Creating a new SwipeTracker40
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: [popx11gestures@system76.com] Connecting Touchégg client signals
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: [popx11gestures@system76.com] Hooking activities view switch desktop gestures
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: [popx11gestures@system76.com] Creating a new SwipeTracker40
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: [popx11gestures@system76.com] Connecting Touchégg client signals
Aug  5 08:58:55 sir-x1extreme system76-power[1102]: [INFO] DBUS Received GetSwitchable() method
Aug  5 08:58:55 sir-x1extreme system76-power[1102]: [INFO] DBUS Received GetGraphics() method
Aug  5 08:58:55 sir-x1extreme system76-power[1102]: [INFO] DBUS Received GetProfile() method
Aug  5 08:58:55 sir-x1extreme gnome-shell[3816610]: gnome-shell-extension-system76-power: power profile was set: 'Balanced'
Aug  5 08:58:56 sir-x1extreme gnome-shell[3816610]: Failed to import DBusMenu, quicklists are not avaialble: Error: Requiring Dbusmenu, version none: Typelib file for namespace 'Dbusmenu' (any version) not found
Aug  5 08:58:56 sir-x1extreme systemd[2684]: Started dbus-:1.2-org.freedesktop.FileManager1@6.service.
Aug  5 08:58:56 sir-x1extreme nautilus[3816687]: Theme parsing error: gtk.css:30:16: not a number
Aug  5 08:58:56 sir-x1extreme nautilus[3816687]: Theme parsing error: gtk-dark.css:9873:19: Junk at end of value for border-radius
Aug  5 08:58:56 sir-x1extreme gnome-shell[3816610]: [VERTICAL-OVERVIEW] starting overrides
Aug  5 08:58:56 sir-x1extreme gnome-shell[3816610]: You may see an error below,#012SecondaryMonitorDisplay is defined as const for some reason#012Since I'm overriding values in that const, thus an error might show up.#012 Feel free to ignore it
Aug  5 08:58:56 sir-x1extreme gnome-shell[3816610]: Some code accessed the property 'SecondaryMonitorDisplay' on the module 'workspacesView'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Aug  5 08:58:56 sir-x1extreme gnome-shell[3816610]: Thank you, please carry on
Aug  5 08:58:56 sir-x1extreme gnome-shell[3816610]: [VERTICAL_OVERVIEW] enabled
Aug  5 08:58:56 sir-x1extreme gsd-media-keys[4131]: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Das Objekt existiert nicht am Pfad »/org/gnome/Shell«
Aug  5 08:58:56 sir-x1extreme gnome-shell[3816610]: Some code accessed the property 'ext' on the module 'extension'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Aug  5 08:58:56 sir-x1extreme gnome-shell[3816610]: meta_sound_player_play_from_theme: assertion 'META_IS_SOUND_PLAYER (player)' failed
Aug  5 08:58:56 sir-x1extreme systemd[2684]: Started dbus-:1.2-org.gnome.Shell.Notifications@3.service.
Aug  5 08:58:57 sir-x1extreme systemd[2684]: Started GNOME Shell on X11.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: [popx11gestures@system76.com] Connection with Touchégg established
Aug  5 08:58:57 sir-x1extreme NetworkManager[1093]: <info>  [1659682737.0999] agent-manager: agent[d6617e43c49d1dbd,:1.1155/org.gnome.Shell.NetworkAgent/1000]: agent registered
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Object .Gjs_ui_workspaceAnimation_WorkspaceGroup (0x55c30b588300), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: == Stack trace for context 0x55c30760c180 ==
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #0   55c307694540 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:230 (1b517b4474c0 @ 37)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #1   55c3076944a8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:225 (1b517b447420 @ 57)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #2   55c3076943c8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:381 (1b517b4479c0 @ 679)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #3   55c307694328 i   resource:///org/gnome/shell/ui/windowManager.js:1632 (1b517b42b060 @ 130)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #4   7ffc6e1bd620 b   self-hosted:1178 (11a1a03b0a10 @ 537)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #5   55c307694288 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1684 (1c47ab0bf6a0 @ 100)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #6   55c307694200 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1768 (1c47ab0bf920 @ 22)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #7   55c3076940f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:156 (1c47ab0bc510 @ 55)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #8   55c307694048 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/executor.js:27 (1c47ab0e4c40 @ 79)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: == Stack trace for context 0x55c30760c180 ==
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #0   55c3076944a8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:211 (1b517b447380 @ 72)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #1   55c3076943c8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:381 (1b517b4479c0 @ 682)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #2   55c307694328 i   resource:///org/gnome/shell/ui/windowManager.js:1632 (1b517b42b060 @ 130)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #3   7ffc6e1bd620 b   self-hosted:1178 (11a1a03b0a10 @ 537)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #4   55c307694288 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1684 (1c47ab0bf6a0 @ 100)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #5   55c307694200 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1768 (1c47ab0bf920 @ 22)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #6   55c3076940f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:156 (1c47ab0bc510 @ 55)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #7   55c307694048 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/executor.js:27 (1c47ab0e4c40 @ 79)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: == Stack trace for context 0x55c30760c180 ==
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #0   55c307694540 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:230 (1b517b4474c0 @ 37)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Object Clutter.Actor (0x55c30b2a9600), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #1   55c3076944a8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:225 (1b517b447420 @ 57)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #2   55c3076943c8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:382 (1b517b4479c0 @ 703)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #3   55c307694328 i   resource:///org/gnome/shell/ui/windowManager.js:1632 (1b517b42b060 @ 130)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #4   7ffc6e1bd620 b   self-hosted:1178 (11a1a03b0a10 @ 537)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #5   55c307694288 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1684 (1c47ab0bf6a0 @ 100)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #6   55c307694200 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1768 (1c47ab0bf920 @ 22)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #7   55c3076940f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:156 (1c47ab0bc510 @ 55)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #8   55c307694048 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/executor.js:27 (1c47ab0e4c40 @ 79)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: == Stack trace for context 0x55c30760c180 ==
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #0   55c307694550 i   resource:///org/gnome/shell/ui/environment.js:272 (11a1a03cc880 @ 373)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #1   55c3076944a8 i   resource:///org/gnome/shell/ui/environment.js:391 (11a1a03ccd80 @ 29)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #2   55c3076943c8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:397 (1b517b4479c0 @ 831)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #3   55c307694328 i   resource:///org/gnome/shell/ui/windowManager.js:1632 (1b517b42b060 @ 130)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #4   7ffc6e1bd620 b   self-hosted:1178 (11a1a03b0a10 @ 537)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #5   55c307694288 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1684 (1c47ab0bf6a0 @ 100)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #6   55c307694200 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1768 (1c47ab0bf920 @ 22)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #7   55c3076940f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:156 (1c47ab0bc510 @ 55)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #8   55c307694048 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/executor.js:27 (1c47ab0e4c40 @ 79)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: == Stack trace for context 0x55c30760c180 ==
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #0   55c307694550 i   resource:///org/gnome/shell/ui/environment.js:286 (11a1a03cc880 @ 467)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #1   55c3076944a8 i   resource:///org/gnome/shell/ui/environment.js:391 (11a1a03ccd80 @ 29)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Object .Gjs_ui_workspaceAnimation_WorkspaceGroup (0x55c30b2a9c40), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #2   55c3076943c8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:397 (1b517b4479c0 @ 831)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #3   55c307694328 i   resource:///org/gnome/shell/ui/windowManager.js:1632 (1b517b42b060 @ 130)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #4   7ffc6e1bd620 b   self-hosted:1178 (11a1a03b0a10 @ 537)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #5   55c307694288 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1684 (1c47ab0bf6a0 @ 100)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #6   55c307694200 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1768 (1c47ab0bf920 @ 22)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #7   55c3076940f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:156 (1c47ab0bc510 @ 55)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #8   55c307694048 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/executor.js:27 (1c47ab0e4c40 @ 79)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: == Stack trace for context 0x55c30760c180 ==
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #0   55c307694658 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:211 (1b517b447380 @ 72)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #1   55c307694550 i   resource:///org/gnome/shell/ui/environment.js:292 (11a1a03cc880 @ 787)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #2   55c3076944a8 i   resource:///org/gnome/shell/ui/environment.js:391 (11a1a03ccd80 @ 29)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #3   55c3076943c8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:397 (1b517b4479c0 @ 831)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #4   55c307694328 i   resource:///org/gnome/shell/ui/windowManager.js:1632 (1b517b42b060 @ 130)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #5   7ffc6e1bd620 b   self-hosted:1178 (11a1a03b0a10 @ 537)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #6   55c307694288 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1684 (1c47ab0bf6a0 @ 100)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #7   55c307694200 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1768 (1c47ab0bf920 @ 22)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #8   55c3076940f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:156 (1c47ab0bc510 @ 55)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #9   55c307694048 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/executor.js:27 (1c47ab0e4c40 @ 79)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: == Stack trace for context 0x55c30760c180 ==
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #0   55c307694540 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:230 (1b517b4474c0 @ 37)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #1   55c3076944a8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:225 (1b517b447420 @ 57)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Object .Gjs_ui_workspaceAnimation_MonitorGroup (0x55c30b5803d0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #2   55c3076943c8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:381 (1b517b4479c0 @ 679)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #3   55c307694328 i   resource:///org/gnome/shell/ui/windowManager.js:1632 (1b517b42b060 @ 130)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #4   7ffc6e1bd620 b   self-hosted:1178 (11a1a03b0a10 @ 537)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #5   55c307694288 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1684 (1c47ab0bf6a0 @ 100)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #6   55c307694200 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1768 (1c47ab0bf920 @ 22)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #7   55c3076940f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:156 (1c47ab0bc510 @ 55)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #8   55c307694048 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/executor.js:27 (1c47ab0e4c40 @ 79)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: == Stack trace for context 0x55c30760c180 ==
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #0   55c3076944a8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:211 (1b517b447380 @ 72)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #1   55c3076943c8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:381 (1b517b4479c0 @ 682)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #2   55c307694328 i   resource:///org/gnome/shell/ui/windowManager.js:1632 (1b517b42b060 @ 130)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #3   7ffc6e1bd620 b   self-hosted:1178 (11a1a03b0a10 @ 537)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #4   55c307694288 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1684 (1c47ab0bf6a0 @ 100)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #5   55c307694200 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1768 (1c47ab0bf920 @ 22)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #6   55c3076940f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:156 (1c47ab0bc510 @ 55)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #7   55c307694048 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/executor.js:27 (1c47ab0e4c40 @ 79)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: == Stack trace for context 0x55c30760c180 ==
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #0   55c307694540 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:230 (1b517b4474c0 @ 37)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #1   55c3076944a8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:225 (1b517b447420 @ 57)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #2   55c3076943c8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:382 (1b517b4479c0 @ 703)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #3   55c307694328 i   resource:///org/gnome/shell/ui/windowManager.js:1632 (1b517b42b060 @ 130)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Object .Gjs_ui_workspaceAnimation_MonitorGroup (0x55c30b5803d0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #4   7ffc6e1bd620 b   self-hosted:1178 (11a1a03b0a10 @ 537)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #5   55c307694288 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1684 (1c47ab0bf6a0 @ 100)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #6   55c307694200 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1768 (1c47ab0bf920 @ 22)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #7   55c3076940f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:156 (1c47ab0bc510 @ 55)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #8   55c307694048 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/executor.js:27 (1c47ab0e4c40 @ 79)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: == Stack trace for context 0x55c30760c180 ==
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #0   55c307694550 i   resource:///org/gnome/shell/ui/environment.js:272 (11a1a03cc880 @ 373)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #1   55c3076944a8 i   resource:///org/gnome/shell/ui/environment.js:391 (11a1a03ccd80 @ 29)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #2   55c3076943c8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:397 (1b517b4479c0 @ 831)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #3   55c307694328 i   resource:///org/gnome/shell/ui/windowManager.js:1632 (1b517b42b060 @ 130)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #4   7ffc6e1bd620 b   self-hosted:1178 (11a1a03b0a10 @ 537)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #5   55c307694288 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1684 (1c47ab0bf6a0 @ 100)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #6   55c307694200 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1768 (1c47ab0bf920 @ 22)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #7   55c3076940f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:156 (1c47ab0bc510 @ 55)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #8   55c307694048 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/executor.js:27 (1c47ab0e4c40 @ 79)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: == Stack trace for context 0x55c30760c180 ==
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #0   55c307694550 i   resource:///org/gnome/shell/ui/environment.js:286 (11a1a03cc880 @ 467)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #1   55c3076944a8 i   resource:///org/gnome/shell/ui/environment.js:391 (11a1a03ccd80 @ 29)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #2   55c3076943c8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:397 (1b517b4479c0 @ 831)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #3   55c307694328 i   resource:///org/gnome/shell/ui/windowManager.js:1632 (1b517b42b060 @ 130)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #4   7ffc6e1bd620 b   self-hosted:1178 (11a1a03b0a10 @ 537)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Object Clutter.Actor (0x55c30b2a9600), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #5   55c307694288 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1684 (1c47ab0bf6a0 @ 100)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #6   55c307694200 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1768 (1c47ab0bf920 @ 22)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #7   55c3076940f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:156 (1c47ab0bc510 @ 55)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #8   55c307694048 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/executor.js:27 (1c47ab0e4c40 @ 79)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: == Stack trace for context 0x55c30760c180 ==
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #0   55c307694658 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:211 (1b517b447380 @ 72)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #1   55c307694550 i   resource:///org/gnome/shell/ui/environment.js:292 (11a1a03cc880 @ 787)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #2   55c3076944a8 i   resource:///org/gnome/shell/ui/environment.js:391 (11a1a03ccd80 @ 29)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #3   55c3076943c8 i   resource:///org/gnome/shell/ui/workspaceAnimation.js:397 (1b517b4479c0 @ 831)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #4   55c307694328 i   resource:///org/gnome/shell/ui/windowManager.js:1632 (1b517b42b060 @ 130)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #5   7ffc6e1bd620 b   self-hosted:1178 (11a1a03b0a10 @ 537)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #6   55c307694288 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1684 (1c47ab0bf6a0 @ 100)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #7   55c307694200 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1768 (1c47ab0bf920 @ 22)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #8   55c3076940f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:156 (1c47ab0bc510 @ 55)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: #9   55c307694048 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/executor.js:27 (1c47ab0e4c40 @ 79)
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Object .Gjs_ui_workspaceAnimation_WorkspaceGroup (0x55c30b5895c0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Object Clutter.Actor (0x55c30b588940), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Object .Gjs_ui_workspaceAnimation_WorkspaceGroup (0x55c30b588f80), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Object .Gjs_ui_workspaceAnimation_MonitorGroup (0x55c30b58cb50), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Object .Gjs_ui_workspaceAnimation_MonitorGroup (0x55c30b58cb50), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Object Clutter.Actor (0x55c30b588940), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug  5 08:58:57 sir-x1extreme gsd-media-keys[4131]: Failed to grab accelerator for keybinding settings:playback-random
Aug  5 08:58:57 sir-x1extreme gsd-media-keys[4131]: Failed to grab accelerator for keybinding settings:rotate-video-lock
Aug  5 08:58:57 sir-x1extreme gsd-media-keys[4131]: Failed to grab accelerator for keybinding settings:playback-repeat
Aug  5 08:58:57 sir-x1extreme gsd-media-keys[4131]: Failed to grab accelerator for keybinding settings:hibernate
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Could not create transient scope for PID 3816777: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 3816777 does not exist.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Could not create transient scope for PID 3816830: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 3816830 does not exist.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Could not create transient scope for PID 3816833: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 3816833 does not exist.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Could not create transient scope for PID 3816836: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 3816836 does not exist.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Could not create transient scope for PID 3816842: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 3816842 does not exist.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Could not create transient scope for PID 3816853: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 3816853 does not exist.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Could not create transient scope for PID 3816856: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 3816856 does not exist.
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Could not create transient scope for PID 3816859: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 3816859 does not exist.
Aug  5 08:58:57 sir-x1extreme nautilus[3816687]: Theme parsing error: gtk-dark.css:9873:19: Junk at end of value for border-radius
Aug  5 08:58:57 sir-x1extreme gnome-shell[3816610]: Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 20).
Aug  5 08:58:57 sir-x1extreme nautilus[3816687]: Theme parsing error: gtk.css:9952:19: Junk at end of value for border-radius
Aug  5 08:58:57 sir-x1extreme nautilus[3816687]: Theme parsing error: gtk-dark.css:9873:19: Junk at end of value for border-radius
Aug  5 08:58:57 sir-x1extreme nautilus[3816687]: Theme parsing error: gtk-dark.css:9873:19: Junk at end of value for border-radius
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55c3079b4300] is on because it needs an allocation.
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55c30a53c720] is on because it needs an allocation.
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55c30a5406b0] is on because it needs an allocation.
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]: Archive:  /tmp/M6F3P1.shell-extension.zip
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/extension.js
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/fields.js
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/icons/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/icons/color-pick.svg
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/de_DE/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/de_DE/LC_MESSAGES/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/de_DE/LC_MESSAGES/gnome-shell-extension-color-picker.mo
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/es_ES/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/es_ES/LC_MESSAGES/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/es_ES/LC_MESSAGES/gnome-shell-extension-color-picker.mo
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/it_IT/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/it_IT/LC_MESSAGES/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/it_IT/LC_MESSAGES/gnome-shell-extension-color-picker.mo
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/nl/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/nl/LC_MESSAGES/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/nl/LC_MESSAGES/gnome-shell-extension-color-picker.mo
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/tr_TR/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/tr_TR/LC_MESSAGES/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/tr_TR/LC_MESSAGES/gnome-shell-extension-color-picker.mo
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/zh_CN/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/zh_CN/LC_MESSAGES/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/locale/zh_CN/LC_MESSAGES/gnome-shell-extension-color-picker.mo
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/prefs.js
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:    creating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/schemas/
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/schemas/org.gnome.shell.extensions.color-picker.gschema.xml
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/schemas/gschemas.compiled
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/stylesheet.css
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:   inflating: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/ui.js
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816880]:  extracting: /home/setuun/.local/share/gnome-shell/extension-updates/color-picker@tuberry/metadata.json
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816610]: GNOME Shell started at Fri Aug 05 2022 08:58:55 GMT+0200 (CEST)
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816610]: Registering session with GDM
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55c3079b4300] is on because it needs an allocation.
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55c30a53c720] is on because it needs an allocation.
Aug  5 08:58:58 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55c30a5406b0] is on because it needs an allocation.
Aug  5 08:58:59 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55c3079b4300] is on because it needs an allocation.
Aug  5 08:58:59 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55c30a53c720] is on because it needs an allocation.
Aug  5 08:58:59 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55c30a5406b0] is on because it needs an allocation.
Aug  5 08:59:01 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55c3079b4300] is on because it needs an allocation.
Aug  5 08:59:01 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55c30a53c720] is on because it needs an allocation.
Aug  5 08:59:01 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55c30a5406b0] is on because it needs an allocation.
Aug  5 08:59:02 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55c3079b4300] is on because it needs an allocation.
Aug  5 08:59:02 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55c30a53dad0] is on because it needs an allocation.
Aug  5 08:59:02 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55c30a541830] is on because it needs an allocation.
Aug  5 08:59:02 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55c30ae26370] is on because it needs an allocation.
Aug  5 08:59:02 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55c30a541f30] is on because it needs an allocation.
Aug  5 08:59:02 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<Gjs_ui_workspaceAnimation_MonitorGroup>:0x55c30a468db0] is on because it needs an allocation.
Aug  5 08:59:02 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55c30bfd55e0] is on because it needs an allocation.
Aug  5 08:59:02 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<Gjs_ui_workspaceAnimation_WorkspaceGroup>:0x55c30bfd52c0] is on because it needs an allocation.
Aug  5 08:59:02 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<ClutterClone>:0x55c30f130460] is on because it needs an allocation.
Aug  5 08:59:02 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<ClutterClone>:0x55c30f1307a0] is on because it needs an allocation.
Aug  5 08:59:07 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55c3079b4300] is on because it needs an allocation.
Aug  5 08:59:07 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55c30a53dad0] is on because it needs an allocation.
Aug  5 08:59:07 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55c30a541830] is on because it needs an allocation.
Aug  5 08:59:07 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55c30ae26370] is on because it needs an allocation.
Aug  5 08:59:07 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55c30a541f30] is on because it needs an allocation.
Aug  5 08:59:11 sir-x1extreme systemd[2684]: Started Application launched by gsd-media-keys.
Aug  5 08:59:11 sir-x1extreme gnome-shell[3816610]: Could not create transient scope for PID 3817034: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 3817034 does not exist.
Aug  5 08:59:11 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55c3079b4300] is on because it needs an allocation.
Aug  5 08:59:11 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55c30ae26370] is on because it needs an allocation.
Aug  5 08:59:11 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55c30a541f30] is on because it needs an allocation.
Aug  5 08:59:11 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55c30ae26f40] is on because it needs an allocation.
Aug  5 08:59:11 sir-x1extreme gnome-shell[3816610]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55c30ae2aa40] is on because it needs an allocation.
Aug  5 08:59:55 sir-x1extreme geoclue[3816676]: Service not used for 60 seconds. Shutting down..
Aug  5 08:59:55 sir-x1extreme systemd[1]: geoclue.service: Deactivated successfully.
Aug  5 09:00:01 sir-x1extreme CRON[3818204]: (root) CMD (timeshift --check --scripted)

**Comment by tuberry** [comment]
@setuun In the related log, I see the color-picker was updated from the extension website. You need restart gnome shell or re-login for the update to take effect. Could reproduce after that?

**Comment by setuun** [comment]
@tuberry looks good for now :+1:
